# The name of the site
site_name: Chomusuke

# Navigation bar
nav:
  - Home: index.md
  - Commands:
    - List of Commands: commands/index.md
    - "AppVeyor: Add Personal Token": commands/appveyor/addtoken.md
    - "AppVeyor: Pick Repository": commands/appveyor/pick.md
    - "AppVeyor: List all Repositories": commands/appveyor/repos.md
    - "AppVeyor: Trigger Build from Default Branch": commands/appveyor/trigger.md
    - "AppVeyor: List Builds for Repository": commands/appveyor/builds.md
    - "GDPR: Dump your Personal Data": commands/gdpr/dump.md
    - "GDPR: Delete your Personal Data": commands/gdpr/forget.md
    - "GitHub: Show all Available Labels": commands/github/labels.md
    - "GitHub: Show Issue Information": commands/github/issue.md
    - "GitHub: Pick Repository": commands/github/pick.md
    - "GitHub: Show Repository Information": commands/github/repo.md
    - "GitHub: List all Repositories": commands/github/repos.md
    - "LoL: Get Match Information": commands/lol/match.md
    - "LoL: Get Basic Profile Information": commands/lol/profile.md
    - "Status: Show APIs Status": commands/status/status.md

# The theme and the colors of it
theme:
  name: material
  palette:
    primary: red
    accent: red
  feature:
    tabs: true
