name: Documentation

on:
  push:
    paths:
      - "**.md"
      - "**.png"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: FullDiveCollective/MarkdownMaterial@master
        with:
          cname: "chomusuke.ml"
      - uses: FullDiveCollective/DeployToBranch@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
